name: pulseboard
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  auto_route: ^10.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  uuid: ^3.0.7
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  mocktail: ^1.0.0


dependency_overrides:
  analyzer: 7.3.0


flutter:
  uses-material-design: true

  
